apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: java-quarkus-hello-docker
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/catoconn-rhmi-tenant/java-quarkus-hello-docker/java-quarkus-hello-docker@sha256:6d06987b788070c3ca282d1edd79fa78ad957552cc9a2bbd65b21f831d112538
        name: my-java-quarkus
        resources: {}
status: {}
