apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-hello-docker
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-hello-docker
    app.kubernetes.io/part-of: java-quarkus-hello-docker
  name: java-quarkus-hello-docker
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-hello-docker
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-hello-docker
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/catoconn-rhmi-tenant/java-quarkus-hello-docker/java-quarkus-hello-docker@sha256:6d06987b788070c3ca282d1edd79fa78ad957552cc9a2bbd65b21f831d112538
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
